"use client";

import "./globals.css";
import QueryProvider from "../components/providers/QueryProvider";
import { MobileLayout } from "../components/ui/MobileLayout";
import Script from "next/script";
import { usePathname } from "next/navigation";

// Metadata는 클라이언트 컴포넌트에서 사용할 수 없으므로 제거하고 head로 처리
// export const metadata: Metadata = {
//   title: "Shesaw",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isPlayground = pathname.startsWith("/playground");

  return (
    <html lang="ko">
      <head>
        <title>Shesaw</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_JS_API_KEY}&libraries=services&autoload=false`}
          strategy="beforeInteractive"
        />
        <QueryProvider>
          {isPlayground ? (
            <div className="min-h-screen bg-gray-50">{children}</div>
          ) : (
            <MobileLayout>{children}</MobileLayout>
          )}
        </QueryProvider>
      </body>
    </html>
  );
}
