import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "../components/providers/QueryProvider";
import { MobileLayout } from "../components/ui/MobileLayout";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Shesaw",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_JS_API_KEY}&libraries=services&autoload=false`}
          strategy="beforeInteractive"
        />
        <QueryProvider>
          <MobileLayout>{children}</MobileLayout>
        </QueryProvider>
      </body>
    </html>
  );
}
